/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/(main)': RouteRecordInfo<
      '/(main)',
      '/',
      Record<never, never>,
      Record<never, never>,
      | '/(main)/dashboard/default'
      | '/(main)/icons/material'
      | '/(main)/icons/tabler'
      | '/(main)/starter'
      | '/(main)/utils/color'
      | '/(main)/utils/shadow'
      | '/(main)/utils/typography'
    >,
    '/(main)/dashboard/default': RouteRecordInfo<
      '/(main)/dashboard/default',
      '/dashboard/default',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/icons/material': RouteRecordInfo<
      '/(main)/icons/material',
      '/icons/material',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/icons/tabler': RouteRecordInfo<
      '/(main)/icons/tabler',
      '/icons/tabler',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/starter': RouteRecordInfo<
      '/(main)/starter',
      '/starter',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/utils/color': RouteRecordInfo<
      '/(main)/utils/color',
      '/utils/color',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/utils/shadow': RouteRecordInfo<
      '/(main)/utils/shadow',
      '/utils/shadow',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/utils/typography': RouteRecordInfo<
      '/(main)/utils/typography',
      '/utils/typography',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/authentication/login': RouteRecordInfo<
      '/authentication/login',
      '/authentication/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/authentication/register': RouteRecordInfo<
      '/authentication/register',
      '/authentication/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/maintenance/error': RouteRecordInfo<
      '/maintenance/error',
      '/maintenance/error',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(main).vue': {
      routes:
        | '/(main)'
        | '/(main)/dashboard/default'
        | '/(main)/icons/material'
        | '/(main)/icons/tabler'
        | '/(main)/starter'
        | '/(main)/utils/color'
        | '/(main)/utils/shadow'
        | '/(main)/utils/typography'
      views:
        | 'default'
    }
    'src/pages/(main)/dashboard/default.vue': {
      routes:
        | '/(main)/dashboard/default'
      views:
        | never
    }
    'src/pages/(main)/icons/material.vue': {
      routes:
        | '/(main)/icons/material'
      views:
        | never
    }
    'src/pages/(main)/icons/tabler.vue': {
      routes:
        | '/(main)/icons/tabler'
      views:
        | never
    }
    'src/pages/(main)/starter.vue': {
      routes:
        | '/(main)/starter'
      views:
        | never
    }
    'src/pages/(main)/utils/color.vue': {
      routes:
        | '/(main)/utils/color'
      views:
        | never
    }
    'src/pages/(main)/utils/shadow.vue': {
      routes:
        | '/(main)/utils/shadow'
      views:
        | never
    }
    'src/pages/(main)/utils/typography.vue': {
      routes:
        | '/(main)/utils/typography'
      views:
        | never
    }
    'src/pages/authentication/login.vue': {
      routes:
        | '/authentication/login'
      views:
        | never
    }
    'src/pages/authentication/register.vue': {
      routes:
        | '/authentication/register'
      views:
        | never
    }
    'src/pages/maintenance/error.vue': {
      routes:
        | '/maintenance/error'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
